config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  #resources :documents #, only: [:new, :create, :show]
  resources :documents do
    member do
      get :export_to_docx
    end
  end
  root "documents#index"
  resources :placeholders
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  mount_uploader :document, DocumentUploader
end

app/models/placeholder.rb
class Placeholder < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  require 'rubyXL'
  require 'rubyXL/convenience_methods/cell'
  require 'rubyXL/convenience_methods/color'
  require 'rubyXL/convenience_methods/font'
  require 'rubyXL/convenience_methods/workbook'
  require 'rubyXL/convenience_methods/worksheet'

  def index
    @documents = Document.all
  end
  def new
    @document = Document.new
  end

  def destroy
    @document = Document.find(params[:id])
    @document.destroy
    redirect_to documents_path
  end

  def create
    @document = Document.new(document_params)
    if @document.save
      DocProcessor.new(@document).process
      redirect_to @document
    else
      render :new
    end
  end

  def show
    @document = Document.find(params[:id])
    @rendered_document = DocProcessor.new(@document).render_document

    original_path = Rails.root.join('public', @document.document_url.gsub(%r{\A/+}, ''))

    if File.exist?(original_path)
      @html_table_original = original_excel_to_html_with_styles(original_path)
    else
      @html_table_original = "<p>File does not exist at path: #{original_path}</p>"
    end

    if @document.processed_document_path.present? && (@document.processed_document_path.include?('.xlsx') || @document.processed_document_path.include?('.xls'))
      path = Rails.root.join('public', @document.processed_document_path.gsub(%r{\A/+}, ''))
      puts "Opening processed document at path: #{path}"
      if File.exist?(path)
        puts "File exists at path: #{path}"
        @html_table = excel_to_html_with_styles(path)
      else
        puts "File does not exist at path: #{path}"
        @html_table = "<p>File does not exist at path: #{path}</p>"
      end
    else
      @html_table = "<p>Invalid or missing document path.</p>"
    end
  end

  private

  def excel_to_html_with_styles(file_path)
    workbook = RubyXL::Parser.parse(file_path)
    html = ""

    workbook.worksheets.each do |worksheet|
      merges = prepare_merge_ranges(worksheet)
      html << "<h2>#{worksheet.sheet_name}</h2>"
      html << "<table border='1'>"
      worksheet.each_with_index do |row, row_idx|
        html << "<tr>"
        row && row.cells.each_with_index do |cell, col_idx|
          next if merges[[row_idx, col_idx]] == :skip
          html << "<td#{style_to_html(cell)}#{merge_html(merges, row_idx, col_idx)}>"
          html << "#{cell && cell.value}</td>"
        end
        html << "</tr>"
      end
      html << "</table>"
    end

    html
  end

  def original_excel_to_html_with_styles(file_path)
    workbook = RubyXL::Parser.parse(file_path)
    html = ""

    workbook.worksheets.each do |worksheet|
      merges = prepare_merge_ranges(worksheet)
      html << "<h2>#{worksheet.sheet_name}</h2>"
      html << "<table border='1'>"
      worksheet.each_with_index do |row, row_idx|
        html << "<tr>"
        row && row.cells.each_with_index do |cell, col_idx|
          next if merges[[row_idx, col_idx]] == :skip
          html << "<td#{style_to_html(cell)}#{merge_html(merges, row_idx, col_idx)}>"
          html << "#{cell && cell.value}</td>"
        end
        html << "</tr>"
      end
      html << "</table>"
    end

    html
  end

  def merge_html(merges, row, col)
    merge = merges[[row, col]]
    return "" unless merge
    " colspan='#{merge[:colspan]}' rowspan='#{merge[:rowspan]}'"
  end

  def prepare_merge_ranges(worksheet)
    merges = {}
    worksheet.merged_cells.each do |range|
      puts "Merged range: #{range.inspect}"
      row_range = range.ref.row_range
      col_range = range.ref.col_range

      (row_range.first..row_range.last).each do |row|
        (col_range.first..col_range.last).each do |col|
          merges[[row, col]] = :skip
        end
      end

      merges[[row_range.first, col_range.first]] = { colspan: col_range.size, rowspan: row_range.size }
    end
    merges
  end

  def style_to_html(cell)
    return "" unless cell

    styles = []
    font_name = cell.font_name
    font_size = cell.font_size
    font_color = cell.font_color
    fill_color = cell.fill_color
    bold = cell.is_bolded
    italic = cell.is_italicized
    h_align = cell.horizontal_alignment
    v_align = cell.vertical_alignment
    wrap_text = cell.change_text_wrap(true)

    # Check border lines
    top_border_line = cell.get_border(:top).to_s != ''
    left_border_line = cell.get_border(:left).to_s != ''
    right_border_line = cell.get_border(:right).to_s != ''
    bottom_border_line = cell.get_border(:bottom).to_s != ''

    top_border_style = cell.get_border(:top) == 'thin' ? '1px solid black' : ''
    left_border_style = cell.get_border(:left) == 'thin' ? '1px solid black' : ''
    right_border_style = cell.get_border(:right) == 'thin' ? '1px solid black' : ''
    bottom_border_style = cell.get_border(:bottom) == 'thin' ? '1px solid black' : ''

    styles << "border-top: #{top_border_style};" if top_border_line
    styles << "border-left: #{left_border_style};" if left_border_line
    styles << "border-right: #{right_border_style};" if right_border_line
    styles << "border-bottom: #{bottom_border_style};" if bottom_border_line

    styles << "font-family:#{font_name};" if font_name
    styles << "font-size:#{font_size}px;" if font_size
    styles << "color:##{font_color};" if font_color
    styles << "background-color:##{fill_color};" if fill_color
    styles << "font-weight:bold;" if bold
    styles << "font-style:italic;" if italic
    styles << "text-align:#{h_align};" if h_align
    styles << "vertical-align:#{v_align};" if v_align
    styles << "white-space: normal; word-wrap: break-word;" if wrap_text

    styles.any? ? " style=\"#{styles.join(' ')}\"" : ""
  end

  def document_params
    params.require(:document).permit(:document)
  end
end

app/controllers/placeholders_controller.rb
class PlaceholdersController < ApplicationController
  def index
    @placeholders = Placeholder.all
  end

  def new
    @placeholder = Placeholder.new
  end

  def create
    @placeholder = Placeholder.new(placeholder_params)
    if @placeholder.save
      redirect_to placeholders_path, notice: 'Placeholder created successfully'
    else
      render :new
    end
  end

  def edit
    @placeholder = Placeholder.find(params[:id])
  end

  def update
    @placeholder = Placeholder.find(params[:id])
    if @placeholder.update(placeholder_params)
      redirect_to placeholders_path, notice: 'Placeholder updated successfully'
    else
      render :edit
    end
  end

  def destroy
    @placeholder = Placeholder.find(params[:id])
    @placeholder.destroy
    redirect_to placeholders_path, notice: 'Placeholder deleted successfully'
  end

  private

  def placeholder_params
    params.require(:placeholder).permit(:key, :value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/placeholders_helper.rb
module PlaceholdersHelper
end

app/views/documents/index.html.erb
<% @documents.each do |document| %>
  <%= link_to document.document, document_path(document) %> | <%= link_to "Destroy", document_path(document.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %> <br>
<% end %>

<%= link_to 'New Document', new_document_path %> <br>
<%== link_to 'Placeholders', placeholders_path%>

app/views/documents/new.html.erb
<%= form_with model: @document, local: true do |form| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>
      <ul>
        <% @document.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :document %>
    <%= form.file_field :document %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/documents/show.html.erb
<p>
  <strong>Original File:</strong>
  <%= link_to @document.document.identifier, @document.document.url %> <br>
  <strong>Download Processed File:</strong>
  <%= link_to 'Download Processed File', @document.processed_document_path if @document.processed_document_path.present? %>
</p>
<p>
  <h1>Document original Details</h1>
  <strong>Original Content:</strong>
<p>

<p>
  <strong>Title:</strong>
  <%= @document.document %>
</p>

<p>
  <strong>Content:</strong>
  <div id="excel">
  <%= raw @html_table_original %>
  </div>
</p>


<p>
  <h1>Document Details</h1>
  <strong>Processed Content:</strong>
<p>
  <strong>Title:</strong>
  <%= @document.document %>
</p>

<div id="excel">
  <%= raw @html_table %>
</div>
</p>

<p>

</p>

<style>
  #excel {
    size: A4;
    margin: 2cm;
  }

  #excel>table {
    width: 21cm;
    height: 29.7cm;
    --margin: 2cm;
    border: none; --1px solid #000;
    padding: 20px;
    box-sizing: border-box;
  }

  table {
    width: 100%;
    --border-collapse: collapse;
  }

  td {
      border: none; /* Remove borders */
      padding: 5px;
  }

  th {
    border: none; /* Remove borders */
    padding: 5px;
    background-color: #f2f2f2;
  }

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DocumentProcessor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/placeholders/edit.html.erb
<h1><%= @placeholder.new_record? ? 'New Placeholder' : 'Edit Placeholder' %></h1>

<%= form_with(model: @placeholder) do |form| %>
  <p>
    <span>
      <%= form.label :key %>
      <%= form.text_area :key, size: "20x1", class: "resizable-input" %>
    </span>
    =>
    <span>
      <%= form.label :value %>
      <%= form.text_area :value, size: "20x1", class: "resizable-input" %>
    </span>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', placeholders_path %>

<style>
  .resizable-input {
    resize: both; /* Allows resizing both horizontally and vertically */
    overflow: auto; /* Adds scrollbar when needed */
    width: auto;
    min-width: 150px; /* Minimum width for better UX */
  }
</style>

app/views/placeholders/index.html.erb
<h1>Placeholders</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th>Id</th>
      <th>Placeholder</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @placeholders.each do |placeholder| %>
      <tr>
        <td><%=placeholder.id%></td>
        <td><span class="text-primary"><%= placeholder.key %></span> => <span class="text-success"><%= placeholder.value %></span></td>
        <td>
          <%= link_to 'Edit', edit_placeholder_path(placeholder), class: 'btn btn-warning btn-sm' %>
          <%= link_to 'Delete', placeholder, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<span><%= link_to 'Documents', documents_path, class: 'btn btn-secondary' %> <%= link_to 'New Placeholder', new_placeholder_path, class: 'btn btn-primary' %></span>

app/views/placeholders/new.html.erb
<h1><%= @placeholder.new_record? ? 'New Placeholder' : 'Edit Placeholder' %></h1>

<%= form_with(model: @placeholder) do |form| %>
  <p>
    <span>
      <%= form.label :key %>
      <%= form.text_area :key, size: "20x1", class: "resizable-input" %>
    </span>
    =>
    <span>
      <%= form.label :value %>
      <%= form.text_area :value, size: "20x1", class: "resizable-input" %>
    </span>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>
<%= link_to 'Back', placeholders_path %>

<style>
  .resizable-input {
    resize: both; /* Allows resizing both horizontally and vertically */
    overflow: auto; /* Adds scrollbar when needed */
    width: auto;
    min-width: 150px; /* Minimum width for better UX */
  }
</style>